### ISSUE TITLE
Support for darwin_arm64

### ISSUE THREAD

**Issue by mathisve** [anschoewe/terraform-provider-curl#4]
Hi,

Our team recently started using M1 macs, which isn't compatible with packages compiled for x86 arch processors. For this reason, we have been getting this error:

```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/anschoewe/curl v0.1.3 does not have a package available for your
│ current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all
│ platforms. Other versions of this provider may have different platforms supported.
```

So we we're wondering if support for darwin_arm64 was on the roadmap.
Thanks.

**Comment by anschoewe** [comment]
let me see what it would take to support this.  I'm hopeful it's easy.

**Comment by mathisve** [comment]
Thank you so much for the quick response and fix!

**Comment by mathisve** [comment]
Sorry for closing and then re-opening. But I think you forgot to tag the commit, so goreleaser didn't run :)

**Comment by anschoewe** [comment]
Patience young padawan :)

**Comment by mathisve** [comment]
hahah sorry!
Much thanks on behalf of our team!
